### ISSUE TITLE
Error parsing URL password

### ISSUE THREAD

**Issue by rbran** [tuanpmt/ESP8266MQTTClient#5]
https://github.com/tuanpmt/ESP8266MQTTClient/blob/252c4cab0b5738bdc811b09253e1c470d2e9cd5f/src/uri_parser.c#L75

The `tolower` will make the password invalid, if the password contain uppercase characters.

**Comment by adolfomendes** [comment]
Nice work Tuan, but I support the rbran request. The tolower function has to go.
